spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/example-community # db 경로
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  mvc:
    hiddenmethod:
      filter:
        enabled: true

logging.level:
  org.hibernate.SQL: debug

server:
  servlet:
    session:
      tracking-modes: cookie